' ----------------------------------------------------------------------------------
' Microsoft Developer & Platform Evangelism
' 
' Copyright (c) Microsoft Corporation. All rights reserved.
' 
' THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
' EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
' OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
' ----------------------------------------------------------------------------------
' The example companies, organizations, products, domain names,
' e-mail addresses, logos, people, places, and events depicted
' herein are fictitious.  No association with any real company,
' organization, product, domain name, email address, logo, person,
' places, or events is intended or should be inferred.
' ----------------------------------------------------------------------------------

'------------------------------------------------------------------------------
'<auto-generated>
'   This code was generated from a template.
'
'   Manual changes to this file may cause unexpected behavior in your application.
'   Manual changes to this file will be overwritten if the code is regenerated.
'</auto-generated>
'------------------------------------------------------------------------------

<Assembly: EdmSchemaAttribute("0d387a4c-1b6e-4337-bdcb-194fa66ffc77")> 
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("MvcMusicStoreModel", "FK__Album__ArtistId__276EDEB3", "Artist", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Artist), "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Album), True)> 
<Assembly: EdmRelationshipAttribute("MvcMusicStoreModel", "FK_Album_Genre", "Genre", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Genre), "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Album), True)> 
<Assembly: EdmRelationshipAttribute("MvcMusicStoreModel", "FK_Cart_Album", "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Album), "Cart", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Cart), True)> 
<Assembly: EdmRelationshipAttribute("MvcMusicStoreModel", "FK_InvoiceLine_Album", "Album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Album), "OrderDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OrderDetail), True)> 
<Assembly: EdmRelationshipAttribute("MvcMusicStoreModel", "FK__InvoiceLi__Invoi__2F10007B", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Order), "OrderDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OrderDetail), True)> 

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Partial Public Class MusicStoreEntities
    Inherits ObjectContext

#Region "Constructors"

    ''' <summary>
    ''' Initializes a new MusicStoreEntities object using the connection string found in the 'MusicStoreEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=MusicStoreEntities", "MusicStoreEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MusicStoreEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MusicStoreEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MusicStoreEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "MusicStoreEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

#End Region

#Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

#End Region

#Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Albums() As ObjectSet(Of Album)
        Get
            If (_Albums Is Nothing) Then
                _Albums = MyBase.CreateObjectSet(Of Album)("Albums")
            End If
            Return _Albums
        End Get
    End Property

    Private _Albums As ObjectSet(Of Album)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Artists() As ObjectSet(Of Artist)
        Get
            If (_Artists Is Nothing) Then
                _Artists = MyBase.CreateObjectSet(Of Artist)("Artists")
            End If
            Return _Artists
        End Get
    End Property

    Private _Artists As ObjectSet(Of Artist)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Carts() As ObjectSet(Of Cart)
        Get
            If (_Carts Is Nothing) Then
                _Carts = MyBase.CreateObjectSet(Of Cart)("Carts")
            End If
            Return _Carts
        End Get
    End Property

    Private _Carts As ObjectSet(Of Cart)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Genres() As ObjectSet(Of Genre)
        Get
            If (_Genres Is Nothing) Then
                _Genres = MyBase.CreateObjectSet(Of Genre)("Genres")
            End If
            Return _Genres
        End Get
    End Property

    Private _Genres As ObjectSet(Of Genre)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Orders() As ObjectSet(Of Order)
        Get
            If (_Orders Is Nothing) Then
                _Orders = MyBase.CreateObjectSet(Of Order)("Orders")
            End If
            Return _Orders
        End Get
    End Property

    Private _Orders As ObjectSet(Of Order)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property OrderDetails() As ObjectSet(Of OrderDetail)
        Get
            If (_OrderDetails Is Nothing) Then
                _OrderDetails = MyBase.CreateObjectSet(Of OrderDetail)("OrderDetails")
            End If
            Return _OrderDetails
        End Get
    End Property

    Private _OrderDetails As ObjectSet(Of OrderDetail)

#End Region
#Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Albums EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAlbums(ByVal album As Album)
        MyBase.AddObject("Albums", album)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Artists EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToArtists(ByVal artist As Artist)
        MyBase.AddObject("Artists", artist)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Carts EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCarts(ByVal cart As Cart)
        MyBase.AddObject("Carts", cart)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Genres EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToGenres(ByVal genre As Genre)
        MyBase.AddObject("Genres", genre)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOrders(ByVal order As Order)
        MyBase.AddObject("Orders", order)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the OrderDetails EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOrderDetails(ByVal orderDetail As OrderDetail)
        MyBase.AddObject("OrderDetails", orderDetail)
    End Sub

#End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MvcMusicStoreModel", Name:="Album")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Album
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Album object.
    ''' </summary>
    ''' <param name="albumId">Initial value of the AlbumId property.</param>
    ''' <param name="genreId">Initial value of the GenreId property.</param>
    ''' <param name="artistId">Initial value of the ArtistId property.</param>
    ''' <param name="title">Initial value of the Title property.</param>
    ''' <param name="price">Initial value of the Price property.</param>
    Public Shared Function CreateAlbum(albumId As Global.System.Int32, genreId As Global.System.Int32, artistId As Global.System.Int32, title As Global.System.String, price As Global.System.Decimal) As Album
        Dim album As Album = New Album
        album.AlbumId = albumId
        album.GenreId = genreId
        album.ArtistId = artistId
        album.Title = title
        album.Price = price
        Return album
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property AlbumId() As Global.System.Int32
        Get
            Return _AlbumId
        End Get
        Set(value As Global.System.Int32)
            If (_AlbumId <> Value) Then
                OnAlbumIdChanging(value)
                ReportPropertyChanging("AlbumId")
                _AlbumId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("AlbumId")
                OnAlbumIdChanged()
            End If
        End Set
    End Property

    Private _AlbumId As Global.System.Int32
    Partial Private Sub OnAlbumIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnAlbumIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property GenreId() As Global.System.Int32
        Get
            Return _GenreId
        End Get
        Set(value As Global.System.Int32)
            OnGenreIdChanging(value)
            ReportPropertyChanging("GenreId")
            _GenreId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("GenreId")
            OnGenreIdChanged()
        End Set
    End Property

    Private _GenreId As Global.System.Int32
    Partial Private Sub OnGenreIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnGenreIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property ArtistId() As Global.System.Int32
        Get
            Return _ArtistId
        End Get
        Set(value As Global.System.Int32)
            OnArtistIdChanging(value)
            ReportPropertyChanging("ArtistId")
            _ArtistId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ArtistId")
            OnArtistIdChanged()
        End Set
    End Property

    Private _ArtistId As Global.System.Int32
    Partial Private Sub OnArtistIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnArtistIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property Title() As Global.System.String
        Get
            Return _Title
        End Get
        Set(value As Global.System.String)
            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property

    Private _Title As Global.System.String
    Partial Private Sub OnTitleChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnTitleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property Price() As Global.System.Decimal
        Get
            Return _Price
        End Get
        Set(value As Global.System.Decimal)
            OnPriceChanging(value)
            ReportPropertyChanging("Price")
            _Price = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Price")
            OnPriceChanged()
        End Set
    End Property

    Private _Price As Global.System.Decimal
    Partial Private Sub OnPriceChanging(value As Global.System.Decimal)
    End Sub

    Partial Private Sub OnPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property AlbumArtUrl() As Global.System.String
        Get
            Return _AlbumArtUrl
        End Get
        Set(value As Global.System.String)
            OnAlbumArtUrlChanging(value)
            ReportPropertyChanging("AlbumArtUrl")
            _AlbumArtUrl = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("AlbumArtUrl")
            OnAlbumArtUrlChanged()
        End Set
    End Property

    Private _AlbumArtUrl As Global.System.String
    Partial Private Sub OnAlbumArtUrlChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnAlbumArtUrlChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK__Album__ArtistId__276EDEB3", "Artist")>
    Public Property Artist() As Artist
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Artist)("MvcMusicStoreModel.FK__Album__ArtistId__276EDEB3", "Artist").Value
        End Get
        Set(value As Artist)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Artist)("MvcMusicStoreModel.FK__Album__ArtistId__276EDEB3", "Artist").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ArtistReference() As EntityReference(Of Artist)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Artist)("MvcMusicStoreModel.FK__Album__ArtistId__276EDEB3", "Artist")
        End Get
        Set(value As EntityReference(Of Artist))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Artist)("MvcMusicStoreModel.FK__Album__ArtistId__276EDEB3", "Artist", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK_Album_Genre", "Genre")>
    Public Property Genre() As Genre
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Genre)("MvcMusicStoreModel.FK_Album_Genre", "Genre").Value
        End Get
        Set(value As Genre)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Genre)("MvcMusicStoreModel.FK_Album_Genre", "Genre").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property GenreReference() As EntityReference(Of Genre)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Genre)("MvcMusicStoreModel.FK_Album_Genre", "Genre")
        End Get
        Set(value As EntityReference(Of Genre))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Genre)("MvcMusicStoreModel.FK_Album_Genre", "Genre", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK_Cart_Album", "Cart")>
    Public Property Carts() As EntityCollection(Of Cart)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Cart)("MvcMusicStoreModel.FK_Cart_Album", "Cart")
        End Get
        Set(value As EntityCollection(Of Cart))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Cart)("MvcMusicStoreModel.FK_Cart_Album", "Cart", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK_InvoiceLine_Album", "OrderDetail")>
    Public Property OrderDetails() As EntityCollection(Of OrderDetail)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrderDetail)("MvcMusicStoreModel.FK_InvoiceLine_Album", "OrderDetail")
        End Get
        Set(value As EntityCollection(Of OrderDetail))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrderDetail)("MvcMusicStoreModel.FK_InvoiceLine_Album", "OrderDetail", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MvcMusicStoreModel", Name:="Artist")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Artist
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Artist object.
    ''' </summary>
    ''' <param name="artistId">Initial value of the ArtistId property.</param>
    Public Shared Function CreateArtist(artistId As Global.System.Int32) As Artist
        Dim artist As Artist = New Artist
        artist.ArtistId = artistId
        Return artist
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property ArtistId() As Global.System.Int32
        Get
            Return _ArtistId
        End Get
        Set(value As Global.System.Int32)
            If (_ArtistId <> Value) Then
                OnArtistIdChanging(value)
                ReportPropertyChanging("ArtistId")
                _ArtistId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ArtistId")
                OnArtistIdChanged()
            End If
        End Set
    End Property

    Private _ArtistId As Global.System.Int32
    Partial Private Sub OnArtistIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnArtistIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set(value As Global.System.String)
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Partial Private Sub OnNameChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnNameChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK__Album__ArtistId__276EDEB3", "Album")>
    Public Property Albums() As EntityCollection(Of Album)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Album)("MvcMusicStoreModel.FK__Album__ArtistId__276EDEB3", "Album")
        End Get
        Set(value As EntityCollection(Of Album))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Album)("MvcMusicStoreModel.FK__Album__ArtistId__276EDEB3", "Album", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MvcMusicStoreModel", Name:="Cart")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Cart
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Cart object.
    ''' </summary>
    ''' <param name="recordId">Initial value of the RecordId property.</param>
    ''' <param name="cartId">Initial value of the CartId property.</param>
    ''' <param name="albumId">Initial value of the AlbumId property.</param>
    ''' <param name="count">Initial value of the Count property.</param>
    ''' <param name="dateCreated">Initial value of the DateCreated property.</param>
    Public Shared Function CreateCart(recordId As Global.System.Int32, cartId As Global.System.String, albumId As Global.System.Int32, count As Global.System.Int32, dateCreated As Global.System.DateTime) As Cart
        Dim cart As Cart = New Cart
        cart.RecordId = recordId
        cart.CartId = cartId
        cart.AlbumId = albumId
        cart.Count = count
        cart.DateCreated = dateCreated
        Return cart
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property RecordId() As Global.System.Int32
        Get
            Return _RecordId
        End Get
        Set(value As Global.System.Int32)
            If (_RecordId <> Value) Then
                OnRecordIdChanging(value)
                ReportPropertyChanging("RecordId")
                _RecordId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("RecordId")
                OnRecordIdChanged()
            End If
        End Set
    End Property

    Private _RecordId As Global.System.Int32
    Partial Private Sub OnRecordIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnRecordIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property CartId() As Global.System.String
        Get
            Return _CartId
        End Get
        Set(value As Global.System.String)
            OnCartIdChanging(value)
            ReportPropertyChanging("CartId")
            _CartId = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("CartId")
            OnCartIdChanged()
        End Set
    End Property

    Private _CartId As Global.System.String
    Partial Private Sub OnCartIdChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnCartIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property AlbumId() As Global.System.Int32
        Get
            Return _AlbumId
        End Get
        Set(value As Global.System.Int32)
            OnAlbumIdChanging(value)
            ReportPropertyChanging("AlbumId")
            _AlbumId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AlbumId")
            OnAlbumIdChanged()
        End Set
    End Property

    Private _AlbumId As Global.System.Int32
    Partial Private Sub OnAlbumIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnAlbumIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property Count() As Global.System.Int32
        Get
            Return _Count
        End Get
        Set(value As Global.System.Int32)
            OnCountChanging(value)
            ReportPropertyChanging("Count")
            _Count = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Count")
            OnCountChanged()
        End Set
    End Property

    Private _Count As Global.System.Int32
    Partial Private Sub OnCountChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnCountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property DateCreated() As Global.System.DateTime
        Get
            Return _DateCreated
        End Get
        Set(value As Global.System.DateTime)
            OnDateCreatedChanging(value)
            ReportPropertyChanging("DateCreated")
            _DateCreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateCreated")
            OnDateCreatedChanged()
        End Set
    End Property

    Private _DateCreated As Global.System.DateTime
    Partial Private Sub OnDateCreatedChanging(value As Global.System.DateTime)
    End Sub

    Partial Private Sub OnDateCreatedChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK_Cart_Album", "Album")>
    Public Property Album() As Album
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Album)("MvcMusicStoreModel.FK_Cart_Album", "Album").Value
        End Get
        Set(value As Album)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Album)("MvcMusicStoreModel.FK_Cart_Album", "Album").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AlbumReference() As EntityReference(Of Album)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Album)("MvcMusicStoreModel.FK_Cart_Album", "Album")
        End Get
        Set(value As EntityReference(Of Album))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Album)("MvcMusicStoreModel.FK_Cart_Album", "Album", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MvcMusicStoreModel", Name:="Genre")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Genre
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Genre object.
    ''' </summary>
    ''' <param name="genreId">Initial value of the GenreId property.</param>
    Public Shared Function CreateGenre(genreId As Global.System.Int32) As Genre
        Dim genre As Genre = New Genre
        genre.GenreId = genreId
        Return genre
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property GenreId() As Global.System.Int32
        Get
            Return _GenreId
        End Get
        Set(value As Global.System.Int32)
            If (_GenreId <> Value) Then
                OnGenreIdChanging(value)
                ReportPropertyChanging("GenreId")
                _GenreId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("GenreId")
                OnGenreIdChanged()
            End If
        End Set
    End Property

    Private _GenreId As Global.System.Int32
    Partial Private Sub OnGenreIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnGenreIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set(value As Global.System.String)
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Partial Private Sub OnNameChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Description() As Global.System.String
        Get
            Return _Description
        End Get
        Set(value As Global.System.String)
            OnDescriptionChanging(value)
            ReportPropertyChanging("Description")
            _Description = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Description")
            OnDescriptionChanged()
        End Set
    End Property

    Private _Description As Global.System.String
    Partial Private Sub OnDescriptionChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnDescriptionChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK_Album_Genre", "Album")>
    Public Property Albums() As EntityCollection(Of Album)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Album)("MvcMusicStoreModel.FK_Album_Genre", "Album")
        End Get
        Set(value As EntityCollection(Of Album))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Album)("MvcMusicStoreModel.FK_Album_Genre", "Album", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MvcMusicStoreModel", Name:="Order")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Order
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Order object.
    ''' </summary>
    ''' <param name="orderId">Initial value of the OrderId property.</param>
    ''' <param name="orderDate">Initial value of the OrderDate property.</param>
    ''' <param name="total">Initial value of the Total property.</param>
    Public Shared Function CreateOrder(orderId As Global.System.Int32, orderDate As Global.System.DateTime, total As Global.System.Decimal) As Order
        Dim order As Order = New Order
        order.OrderId = orderId
        order.OrderDate = orderDate
        order.Total = total
        Return order
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property OrderId() As Global.System.Int32
        Get
            Return _OrderId
        End Get
        Set(value As Global.System.Int32)
            If (_OrderId <> Value) Then
                OnOrderIdChanging(value)
                ReportPropertyChanging("OrderId")
                _OrderId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("OrderId")
                OnOrderIdChanged()
            End If
        End Set
    End Property

    Private _OrderId As Global.System.Int32
    Partial Private Sub OnOrderIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnOrderIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property OrderDate() As Global.System.DateTime
        Get
            Return _OrderDate
        End Get
        Set(value As Global.System.DateTime)
            OnOrderDateChanging(value)
            ReportPropertyChanging("OrderDate")
            _OrderDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OrderDate")
            OnOrderDateChanged()
        End Set
    End Property

    Private _OrderDate As Global.System.DateTime
    Partial Private Sub OnOrderDateChanging(value As Global.System.DateTime)
    End Sub

    Partial Private Sub OnOrderDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Username() As Global.System.String
        Get
            Return _Username
        End Get
        Set(value As Global.System.String)
            OnUsernameChanging(value)
            ReportPropertyChanging("Username")
            _Username = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Username")
            OnUsernameChanged()
        End Set
    End Property

    Private _Username As Global.System.String
    Partial Private Sub OnUsernameChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnUsernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property FirstName() As Global.System.String
        Get
            Return _FirstName
        End Get
        Set(value As Global.System.String)
            OnFirstNameChanging(value)
            ReportPropertyChanging("FirstName")
            _FirstName = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("FirstName")
            OnFirstNameChanged()
        End Set
    End Property

    Private _FirstName As Global.System.String
    Partial Private Sub OnFirstNameChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnFirstNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property LastName() As Global.System.String
        Get
            Return _LastName
        End Get
        Set(value As Global.System.String)
            OnLastNameChanging(value)
            ReportPropertyChanging("LastName")
            _LastName = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("LastName")
            OnLastNameChanged()
        End Set
    End Property

    Private _LastName As Global.System.String
    Partial Private Sub OnLastNameChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnLastNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Address() As Global.System.String
        Get
            Return _Address
        End Get
        Set(value As Global.System.String)
            OnAddressChanging(value)
            ReportPropertyChanging("Address")
            _Address = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Address")
            OnAddressChanged()
        End Set
    End Property

    Private _Address As Global.System.String
    Partial Private Sub OnAddressChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnAddressChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set(value As Global.System.String)
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property

    Private _City As Global.System.String
    Partial Private Sub OnCityChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnCityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property State() As Global.System.String
        Get
            Return _State
        End Get
        Set(value As Global.System.String)
            OnStateChanging(value)
            ReportPropertyChanging("State")
            _State = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("State")
            OnStateChanged()
        End Set
    End Property

    Private _State As Global.System.String
    Partial Private Sub OnStateChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnStateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property PostalCode() As Global.System.String
        Get
            Return _PostalCode
        End Get
        Set(value As Global.System.String)
            OnPostalCodeChanging(value)
            ReportPropertyChanging("PostalCode")
            _PostalCode = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("PostalCode")
            OnPostalCodeChanged()
        End Set
    End Property

    Private _PostalCode As Global.System.String
    Partial Private Sub OnPostalCodeChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnPostalCodeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Country() As Global.System.String
        Get
            Return _Country
        End Get
        Set(value As Global.System.String)
            OnCountryChanging(value)
            ReportPropertyChanging("Country")
            _Country = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Country")
            OnCountryChanged()
        End Set
    End Property

    Private _Country As Global.System.String
    Partial Private Sub OnCountryChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnCountryChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Phone() As Global.System.String
        Get
            Return _Phone
        End Get
        Set(value As Global.System.String)
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property

    Private _Phone As Global.System.String
    Partial Private Sub OnPhoneChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnPhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Email() As Global.System.String
        Get
            Return _Email
        End Get
        Set(value As Global.System.String)
            OnEmailChanging(value)
            ReportPropertyChanging("Email")
            _Email = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Email")
            OnEmailChanged()
        End Set
    End Property

    Private _Email As Global.System.String
    Partial Private Sub OnEmailChanging(value As Global.System.String)
    End Sub

    Partial Private Sub OnEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property Total() As Global.System.Decimal
        Get
            Return _Total
        End Get
        Set(value As Global.System.Decimal)
            OnTotalChanging(value)
            ReportPropertyChanging("Total")
            _Total = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Total")
            OnTotalChanged()
        End Set
    End Property

    Private _Total As Global.System.Decimal
    Partial Private Sub OnTotalChanging(value As Global.System.Decimal)
    End Sub

    Partial Private Sub OnTotalChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK__InvoiceLi__Invoi__2F10007B", "OrderDetail")>
    Public Property OrderDetails() As EntityCollection(Of OrderDetail)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrderDetail)("MvcMusicStoreModel.FK__InvoiceLi__Invoi__2F10007B", "OrderDetail")
        End Get
        Set(value As EntityCollection(Of OrderDetail))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrderDetail)("MvcMusicStoreModel.FK__InvoiceLi__Invoi__2F10007B", "OrderDetail", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MvcMusicStoreModel", Name:="OrderDetail")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class OrderDetail
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new OrderDetail object.
    ''' </summary>
    ''' <param name="orderDetailId">Initial value of the OrderDetailId property.</param>
    ''' <param name="orderId">Initial value of the OrderId property.</param>
    ''' <param name="albumId">Initial value of the AlbumId property.</param>
    ''' <param name="quantity">Initial value of the Quantity property.</param>
    ''' <param name="unitPrice">Initial value of the UnitPrice property.</param>
    Public Shared Function CreateOrderDetail(orderDetailId As Global.System.Int32, orderId As Global.System.Int32, albumId As Global.System.Int32, quantity As Global.System.Int32, unitPrice As Global.System.Decimal) As OrderDetail
        Dim orderDetail As OrderDetail = New OrderDetail
        orderDetail.OrderDetailId = orderDetailId
        orderDetail.OrderId = orderId
        orderDetail.AlbumId = albumId
        orderDetail.Quantity = quantity
        orderDetail.UnitPrice = unitPrice
        Return orderDetail
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property OrderDetailId() As Global.System.Int32
        Get
            Return _OrderDetailId
        End Get
        Set(value As Global.System.Int32)
            If (_OrderDetailId <> Value) Then
                OnOrderDetailIdChanging(value)
                ReportPropertyChanging("OrderDetailId")
                _OrderDetailId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("OrderDetailId")
                OnOrderDetailIdChanged()
            End If
        End Set
    End Property

    Private _OrderDetailId As Global.System.Int32
    Partial Private Sub OnOrderDetailIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnOrderDetailIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property OrderId() As Global.System.Int32
        Get
            Return _OrderId
        End Get
        Set(value As Global.System.Int32)
            OnOrderIdChanging(value)
            ReportPropertyChanging("OrderId")
            _OrderId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OrderId")
            OnOrderIdChanged()
        End Set
    End Property

    Private _OrderId As Global.System.Int32
    Partial Private Sub OnOrderIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnOrderIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property AlbumId() As Global.System.Int32
        Get
            Return _AlbumId
        End Get
        Set(value As Global.System.Int32)
            OnAlbumIdChanging(value)
            ReportPropertyChanging("AlbumId")
            _AlbumId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AlbumId")
            OnAlbumIdChanged()
        End Set
    End Property

    Private _AlbumId As Global.System.Int32
    Partial Private Sub OnAlbumIdChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnAlbumIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property Quantity() As Global.System.Int32
        Get
            Return _Quantity
        End Get
        Set(value As Global.System.Int32)
            OnQuantityChanging(value)
            ReportPropertyChanging("Quantity")
            _Quantity = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Quantity")
            OnQuantityChanged()
        End Set
    End Property

    Private _Quantity As Global.System.Int32
    Partial Private Sub OnQuantityChanging(value As Global.System.Int32)
    End Sub

    Partial Private Sub OnQuantityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property UnitPrice() As Global.System.Decimal
        Get
            Return _UnitPrice
        End Get
        Set(value As Global.System.Decimal)
            OnUnitPriceChanging(value)
            ReportPropertyChanging("UnitPrice")
            _UnitPrice = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UnitPrice")
            OnUnitPriceChanged()
        End Set
    End Property

    Private _UnitPrice As Global.System.Decimal
    Partial Private Sub OnUnitPriceChanging(value As Global.System.Decimal)
    End Sub

    Partial Private Sub OnUnitPriceChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK_InvoiceLine_Album", "Album")>
    Public Property Album() As Album
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Album)("MvcMusicStoreModel.FK_InvoiceLine_Album", "Album").Value
        End Get
        Set(value As Album)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Album)("MvcMusicStoreModel.FK_InvoiceLine_Album", "Album").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AlbumReference() As EntityReference(Of Album)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Album)("MvcMusicStoreModel.FK_InvoiceLine_Album", "Album")
        End Get
        Set(value As EntityReference(Of Album))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Album)("MvcMusicStoreModel.FK_InvoiceLine_Album", "Album", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MvcMusicStoreModel", "FK__InvoiceLi__Invoi__2F10007B", "Order")>
    Public Property Order() As Order
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("MvcMusicStoreModel.FK__InvoiceLi__Invoi__2F10007B", "Order").Value
        End Get
        Set(value As Order)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("MvcMusicStoreModel.FK__InvoiceLi__Invoi__2F10007B", "Order").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OrderReference() As EntityReference(Of Order)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("MvcMusicStoreModel.FK__InvoiceLi__Invoi__2F10007B", "Order")
        End Get
        Set(value As EntityReference(Of Order))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Order)("MvcMusicStoreModel.FK__InvoiceLi__Invoi__2F10007B", "Order", value)
            End If
        End Set
    End Property

#End Region
End Class

#End Region

