//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MathServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MathServer.IMathServer")]
    public interface IMathServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathServer/AddSlow", ReplyAction="http://tempuri.org/IMathServer/AddSlowResponse")]
        int AddSlow(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathServer/AddSlow", ReplyAction="http://tempuri.org/IMathServer/AddSlowResponse")]
        System.IAsyncResult BeginAddSlow(int A, int B, System.AsyncCallback callback, object asyncState);
        
        int EndAddSlow(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathServer/AddFast", ReplyAction="http://tempuri.org/IMathServer/AddFastResponse")]
        int AddFast(int A, int B);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMathServer/AddFast", ReplyAction="http://tempuri.org/IMathServer/AddFastResponse")]
        System.IAsyncResult BeginAddFast(int A, int B, System.AsyncCallback callback, object asyncState);
        
        int EndAddFast(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMathServerChannel : Client.MathServer.IMathServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AddSlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddSlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AddFastCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddFastCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MathServerClient : System.ServiceModel.ClientBase<Client.MathServer.IMathServer>, Client.MathServer.IMathServer {
        
        private BeginOperationDelegate onBeginAddSlowDelegate;
        
        private EndOperationDelegate onEndAddSlowDelegate;
        
        private System.Threading.SendOrPostCallback onAddSlowCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddFastDelegate;
        
        private EndOperationDelegate onEndAddFastDelegate;
        
        private System.Threading.SendOrPostCallback onAddFastCompletedDelegate;
        
        public MathServerClient() {
        }
        
        public MathServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AddSlowCompletedEventArgs> AddSlowCompleted;
        
        public event System.EventHandler<AddFastCompletedEventArgs> AddFastCompleted;
        
        public int AddSlow(int A, int B) {
            return base.Channel.AddSlow(A, B);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddSlow(int A, int B, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddSlow(A, B, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndAddSlow(System.IAsyncResult result) {
            return base.Channel.EndAddSlow(result);
        }
        
        private System.IAsyncResult OnBeginAddSlow(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int A = ((int)(inValues[0]));
            int B = ((int)(inValues[1]));
            return this.BeginAddSlow(A, B, callback, asyncState);
        }
        
        private object[] OnEndAddSlow(System.IAsyncResult result) {
            int retVal = this.EndAddSlow(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddSlowCompleted(object state) {
            if ((this.AddSlowCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddSlowCompleted(this, new AddSlowCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddSlowAsync(int A, int B) {
            this.AddSlowAsync(A, B, null);
        }
        
        public void AddSlowAsync(int A, int B, object userState) {
            if ((this.onBeginAddSlowDelegate == null)) {
                this.onBeginAddSlowDelegate = new BeginOperationDelegate(this.OnBeginAddSlow);
            }
            if ((this.onEndAddSlowDelegate == null)) {
                this.onEndAddSlowDelegate = new EndOperationDelegate(this.OnEndAddSlow);
            }
            if ((this.onAddSlowCompletedDelegate == null)) {
                this.onAddSlowCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddSlowCompleted);
            }
            base.InvokeAsync(this.onBeginAddSlowDelegate, new object[] {
                        A,
                        B}, this.onEndAddSlowDelegate, this.onAddSlowCompletedDelegate, userState);
        }
        
        public int AddFast(int A, int B) {
            return base.Channel.AddFast(A, B);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddFast(int A, int B, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddFast(A, B, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndAddFast(System.IAsyncResult result) {
            return base.Channel.EndAddFast(result);
        }
        
        private System.IAsyncResult OnBeginAddFast(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int A = ((int)(inValues[0]));
            int B = ((int)(inValues[1]));
            return this.BeginAddFast(A, B, callback, asyncState);
        }
        
        private object[] OnEndAddFast(System.IAsyncResult result) {
            int retVal = this.EndAddFast(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddFastCompleted(object state) {
            if ((this.AddFastCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddFastCompleted(this, new AddFastCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddFastAsync(int A, int B) {
            this.AddFastAsync(A, B, null);
        }
        
        public void AddFastAsync(int A, int B, object userState) {
            if ((this.onBeginAddFastDelegate == null)) {
                this.onBeginAddFastDelegate = new BeginOperationDelegate(this.OnBeginAddFast);
            }
            if ((this.onEndAddFastDelegate == null)) {
                this.onEndAddFastDelegate = new EndOperationDelegate(this.OnEndAddFast);
            }
            if ((this.onAddFastCompletedDelegate == null)) {
                this.onAddFastCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddFastCompleted);
            }
            base.InvokeAsync(this.onBeginAddFastDelegate, new object[] {
                        A,
                        B}, this.onEndAddFastDelegate, this.onAddFastCompletedDelegate, userState);
        }
    }
}
